keystore:
  KeyStoreFileAbsPath: "/Users/zhuliting/go/zx-demo/config/keystore"
  KeyStorePasswd: "11111111"

endpoint:
  LiteClientRpcEndpoint: "http://127.0.0.1:1317"
  RPCEndpoint: "http://127.0.0.1:26657"

ChainID: "nch-chain"

feeParams:
  TxDefaultGas: 20000000
  TxDefaultFeeAmount: 1000000000000